#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Dec 15, 2022 12:41:33 PM CST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import simplestyle_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran:
       return
    style = ttk.Style()
    if sys.platform == "win32":
       style.theme_use('winnative')
    style.configure('.',background=_bgcolor)
    style.configure('.',foreground=_fgcolor)
    style.configure('.',font='TkDefaultFont')
    style.map('.',background =
       [('selected', _compcolor), ('active',_ana2color)])
    if _bgmode == 'dark':
       style.map('.',foreground =
         [('selected', 'white'), ('active','white')])
    else:
       style.map('.',foreground =
         [('selected', 'black'), ('active','black')])
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x230+1076+594")
        top.minsize(1, 1)
        top.maxsize(4225, 1410)
        top.resizable(0,  0)
        top.title("Style Demo 1")

        self.top = top

        _style_code()
        self.TButton1 = ttk.Button(self.top)
        self.TButton1.place(x=110, y=80, height=48, width=183)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Tbutton''')
        self.TButton1.configure(compound='left')
        self.btnMyStyle = tk.Button(self.top)
        self.btnMyStyle.place(x=320, y=90, height=33, width=173)
        self.btnMyStyle.configure(activebackground="beige")
        self.btnMyStyle.configure(borderwidth="2")
        self.btnMyStyle.configure(command=simplestyle_support.on_btnMyStyle)
        self.btnMyStyle.configure(compound='left')
        self.btnMyStyle.configure(text='''My Style''')

def start_up():
    simplestyle_support.main()

if __name__ == '__main__':
    simplestyle_support.main()




