#############################################################################
# Generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#  Aug 05, 2022 03:45:23 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top76 {base} {
    global vTcl
    if {$base == ""} {
        set base .top76
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m40" -background $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 652x605+1011+590
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1265 770
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Pinger"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "pinger" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    labelframe $top.lab38 \
        -font TkDefaultFont -foreground black -text {Ping To Sites:} \
        -background $vTcl(actual_gui_bg) -height 345 -highlightcolor black \
        -width 250 
    vTcl:DefineAlias "$top.lab38" "lframePingTo" vTcl:WidgetProc "pinger" 1
    set site_3_0 $top.lab38
    radiobutton $site_3_0.rad61 \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_rbSiteClick \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text 8.8.8.8 \
        -textvariable rb1display -value 0 -variable selectbutton -width 155 
    vTcl:DefineAlias "$site_3_0.rad61" "rbsite1" vTcl:WidgetProc "pinger" 1
    radiobutton $site_3_0.rad62 \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_rbSiteClick \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text {Google2 - 8.8.4.4} \
        -textvariable rb2disp -value 1 -variable selectedButton -width 155 
    vTcl:DefineAlias "$site_3_0.rad62" "rbsite2" vTcl:WidgetProc "pinger" 1
    radiobutton $site_3_0.rad63 \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_rbSiteClick \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text {Zaphod - 192.168.1.12 } \
        -textvariable rb3disp -value 2 -variable selectbutton -width 215 
    vTcl:DefineAlias "$site_3_0.rad63" "rbsite3" vTcl:WidgetProc "pinger" 1
    radiobutton $site_3_0.rad64 \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_rbSiteClick \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text 192.168.1.243 \
        -textvariable rb4display -value 3 -variable selectbutton -width 155 
    vTcl:DefineAlias "$site_3_0.rad64" "rbsite4" vTcl:WidgetProc "pinger" 1
    radiobutton $site_3_0.rad65 \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_rbSiteClick \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -value 4 -variable selectbutton \
        -width 155 
    vTcl:DefineAlias "$site_3_0.rad65" "rbsite5" vTcl:WidgetProc "pinger" 1
    place $site_3_0.rad61 \
        -in $site_3_0 -x 20 -y 40 -width 215 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad62 \
        -in $site_3_0 -x 20 -y 70 -width 215 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad63 \
        -in $site_3_0 -x 20 -y 100 -width 215 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad64 \
        -in $site_3_0 -x 20 -y 130 -width 215 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad65 \
        -in $site_3_0 -x 20 -y 160 -width 215 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra39 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 255 -highlightcolor black -width 645 
    vTcl:DefineAlias "$top.fra39" "frameTxtBox" vTcl:WidgetProc "pinger" 1
    set site_3_0 $top.fra39
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr55 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr55" "txtErrors" vTcl:WidgetProc "pinger" 1

    $site_3_0.scr55.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_3_0.scr55 \
        -in $site_3_0 -x 5 -y 3 -width 636 -relwidth 0 -height 248 \
        -relheight 0 -anchor nw -bordermode ignore 
    menu $top.m40 \
        -activebackground #d8d8d8 -activeforeground #000000 \
        -background $vTcl(actual_gui_menu_bg) -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    
set site_3_0 $top.m40
    $top.m40 add cascade \
        -menu "$top.m40.men41" -activebackground #d9d9d9 \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -label File 
    menu $site_3_0.men41 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font TkMenuFont \
        -foreground black -tearoff 0 
    $site_3_0.men41 add command \
        -activebackground #d8d8d8 -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command {#mnuFileExit} \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -label Exit 
    
set site_3_0 $top.m40
    $top.m40 add cascade \
        -menu "$top.m40.men42" -activebackground #d9d9d9 \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -label Help 
    menu $site_3_0.men42 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font TkMenuFont \
        -foreground black -tearoff 0 
    $site_3_0.men42 add command \
        -activebackground #d8d8d8 -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command {#mnuHelpAbout} \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -label About 
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 175 -highlightcolor black -width 395 
    vTcl:DefineAlias "$top.fra43" "frameDisplay" vTcl:WidgetProc "pinger" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {External IP: } 
    vTcl:DefineAlias "$site_3_0.lab44" "Label1" vTcl:WidgetProc "pinger" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -textvariable ExternalIP 
    vTcl:DefineAlias "$site_3_0.lab45" "lblExternalIP" vTcl:WidgetProc "pinger" 1
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Last Ping Time: } 
    vTcl:DefineAlias "$site_3_0.lab46" "Label3" vTcl:WidgetProc "pinger" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text Label -textvariable LastPingTime 
    vTcl:DefineAlias "$site_3_0.lab47" "lblLastPing" vTcl:WidgetProc "pinger" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Pings Done: } 
    vTcl:DefineAlias "$site_3_0.lab48" "Label5" vTcl:WidgetProc "pinger" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text Label -textvariable PingsDone 
    vTcl:DefineAlias "$site_3_0.lab49" "lblPingsDone" vTcl:WidgetProc "pinger" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Slow Pings: } 
    vTcl:DefineAlias "$site_3_0.lab50" "Label7" vTcl:WidgetProc "pinger" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text Label -textvariable SlowPings 
    vTcl:DefineAlias "$site_3_0.lab51" "lblSlowPings" vTcl:WidgetProc "pinger" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Failed Pings: } 
    vTcl:DefineAlias "$site_3_0.lab52" "Label9" vTcl:WidgetProc "pinger" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text Label -textvariable FailedPings 
    vTcl:DefineAlias "$site_3_0.lab53" "lblFailedPings" vTcl:WidgetProc "pinger" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 3 -y 15 -width 147 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 155 -y 10 -width 226 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 3 -y 45 -width 147 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 155 -y 40 -width 226 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 4 -y 76 -width 147 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 155 -y 70 -width 226 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 4 -y 105 -width 147 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 155 -y 100 -width 226 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 4 -y 135 -width 147 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 155 -y 130 -width 226 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra54 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 165 -highlightcolor black -width 395 
    vTcl:DefineAlias "$top.fra54" "frameOptions" vTcl:WidgetProc "pinger" 1
    set site_3_0 $top.fra54
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Delay between Pings (in secs): } 
    vTcl:DefineAlias "$site_3_0.lab56" "Label11" vTcl:WidgetProc "pinger" 1
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Times to ping (0 = forever): } 
    vTcl:DefineAlias "$site_3_0.lab57" "Label12" vTcl:WidgetProc "pinger" 1
    spinbox $site_3_0.spi58 \
        -activebackground #f9f9f9 -background white -font TkTextFont \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black \
        -textvariable PingDelay -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi58" "spinPingDelay" vTcl:WidgetProc "pinger" 1
    spinbox $site_3_0.spi59 \
        -activebackground #f9f9f9 -background white -font TkTextFont \
        -foreground black -from 0.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black \
        -textvariable TimesToPing -to 10000.0 
    vTcl:DefineAlias "$site_3_0.spi59" "spinTimesToPing" vTcl:WidgetProc "pinger" 1
    button $site_3_0.but60 \
        -activebackground #d9d9d9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command OnBtnStart \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -state active -text Start 
    vTcl:DefineAlias "$site_3_0.but60" "btnStart" vTcl:WidgetProc "pinger" 1
    place $site_3_0.lab56 \
        -in $site_3_0 -x 10 -y 10 -width 252 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 13 -y 40 -width 252 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi58 \
        -in $site_3_0 -x 260 -y 10 -width 68 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi59 \
        -in $site_3_0 -x 261 -y 40 -width 118 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but60 \
        -in $site_3_0 -x 160 -y 100 -width 107 -relwidth 0 -height 37 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab38 \
        -in $top -x 400 -y 0 -width 250 -relwidth 0 -height 340 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra39 \
        -in $top -x 4 -y 341 -width 645 -relwidth 0 -height 255 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra43 \
        -in $top -x 4 -y 0 -width 395 -relwidth 0 -height 175 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra54 \
        -in $top -x 4 -y 175 -width 395 -relwidth 0 -height 165 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top77 {base} {
    global vTcl
    if {$base == ""} {
        set base .top77
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 459x535+2057+88
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1265 770
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "About"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "About" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label $top.lab38 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text Label -textvariable ProgNameDisplay 
    vTcl:DefineAlias "$top.lab38" "lblProgName" vTcl:WidgetProc "About" 1
    set ProgNameDisplay {Label}
    label $top.lab39 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text Label -textvariable VersionDisplay 
    vTcl:DefineAlias "$top.lab39" "lblVersion" vTcl:WidgetProc "About" 1
    set VersionDisplay {Label}
    label $top.lab40 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text Label -textvariable AuthorDisplay 
    vTcl:DefineAlias "$top.lab40" "lblAuthor" vTcl:WidgetProc "About" 1
    set AuthorDisplay {Label}
    label $top.lab41 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text Label -textvariable CopyrightDisplay 
    vTcl:DefineAlias "$top.lab41" "lblCopyright" vTcl:WidgetProc "About" 1
    set CopyrightDisplay {Label}
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr42 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr42" "Scrolledtext1" vTcl:WidgetProc "About" 1

    $top.scr42.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap word
    button $top.but43 \
        -activebackground #d9d9d9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command on_btnAboutDismiss \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Dismiss 
    vTcl:DefineAlias "$top.but43" "btnAboutDismiss" vTcl:WidgetProc "About" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab38 \
        -in $top -x 10 -y 20 -width 436 -relwidth 0 -height 29 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab39 \
        -in $top -x 10 -y 52 -width 436 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.lab40 \
        -in $top -x 10 -y 84 -width 436 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.lab41 \
        -in $top -x 10 -y 116 -width 436 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.scr42 \
        -in $top -x 10 -y 160 -width 438 -relwidth 0 -height 291 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but43 \
        -in $top -x 130 -y 470 -width 177 -relwidth 0 -height 37 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top76 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top77 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}

