#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.2
#  in conjunction with Tcl version 8.6
#    Feb 01, 2022 02:11:27 PM CST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import DualForms_support

class MainForm:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("764x506+649+278")
        top.minsize(1, 1)
        top.maxsize(3585, 1050)
        top.resizable(0,  0)
        top.title("MainForm")
        top.configure(highlightcolor="black")

        self.top = top
        self.SecondFormData = tk.StringVar()
        self.che46 = tk.IntVar()

        self.btnExit = tk.Button(self.top)
        self.btnExit.place(x=590, y=30, height=29, width=89)
        self.btnExit.configure(activebackground="#f9f9f9")
        self.btnExit.configure(command=DualForms_support.on_btnExit)
        self.btnExit.configure(font="-family {DejaVu Sans} -size 10 -weight bold -slant italic")
        self.btnExit.configure(text='''Exit''')

        self.Checkbutton1 = tk.Checkbutton(self.top)
        self.Checkbutton1.place(x=90, y=100, height=31, width=263)
        self.Checkbutton1.configure(activebackground="#f9f9f9")
        self.Checkbutton1.configure(anchor='w')
        self.Checkbutton1.configure(borderwidth="2")
        self.Checkbutton1.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(relief="ridge")
        self.Checkbutton1.configure(text='''Has second form been run?''')
        self.Checkbutton1.configure(variable=self.che46)

        self.Label1 = tk.Label(self.top)
        self.Label1.place(x=90, y=220, height=31, width=418)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(borderwidth="2")
        self.Label1.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.Label1.configure(relief="ridge")
        self.Label1.configure(text='''Label''')
        self.Label1.configure(textvariable=self.SecondFormData)
        self.SecondFormData.set('''Label''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(x=90, y=190, height=21, width=323)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(anchor='w')
        self.Label2.configure(font="-family {DejaVu Sans} -size 10 -weight bold -slant italic")
        self.Label2.configure(text='''Data passed from second form:''')

        self.btnLaunch = tk.Button(self.top)
        self.btnLaunch.place(x=90, y=300, height=31, width=225)
        self.btnLaunch.configure(activebackground="#f9f9f9")
        self.btnLaunch.configure(command=DualForms_support.on_btnLaunch)
        self.btnLaunch.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.btnLaunch.configure(text='''Launch Second Form''')

class ChildForm:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("760x506+688+271")
        top.minsize(1, 1)
        top.maxsize(3585, 1050)
        top.resizable(0,  0)
        top.title("Second Form")
        top.configure(background="cornflowerblue")
        top.configure(highlightcolor="black")

        self.top = top
        self.PassBack = tk.StringVar()
        self.RunCount = tk.StringVar()

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(x=120, y=240, height=31, width=516)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(selectbackground="blue")
        self.Entry1.configure(selectforeground="white")
        self.Entry1.configure(textvariable=self.PassBack)
        self.PassBack.set('''PassBack''')

        self.btnDismiss = tk.Button(self.top)
        self.btnDismiss.place(x=620, y=20, height=29, width=99)
        self.btnDismiss.configure(activebackground="#f9f9f9")
        self.btnDismiss.configure(command=DualForms_support.on_btnDismiss)
        self.btnDismiss.configure(font="-family {DejaVu Sans} -size 10 -weight bold -slant italic")
        self.btnDismiss.configure(text='''Dismiss''')

        self.Label1_1 = tk.Label(self.top)
        self.Label1_1.place(x=110, y=50, height=49, width=466)
        self.Label1_1.configure(activebackground="#6495ed")
        self.Label1_1.configure(background="#6495ed")
        self.Label1_1.configure(font="-family {DejaVu Sans} -size 12 -weight bold -slant italic")
        self.Label1_1.configure(text='''This is the Second Form!''')

        self.Label2_1 = tk.Label(self.top)
        self.Label2_1.place(x=120, y=210, height=19, width=416)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(anchor='w')
        self.Label2_1.configure(background="#6495ed")
        self.Label2_1.configure(font="-family {DejaVu Sans} -size 10 -weight bold -slant italic")
        self.Label2_1.configure(text='''Data to pass back to the Main form:''')

        self.Label3 = tk.Label(self.top)
        self.Label3.place(x=120, y=120, height=19, width=266)
        self.Label3.configure(activebackground="#6495ed")
        self.Label3.configure(anchor='e')
        self.Label3.configure(background="#6495ed")
        self.Label3.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.Label3.configure(text='''Times this form has been shown:''')

        self.Label4 = tk.Label(self.top)
        self.Label4.place(x=390, y=115, height=29, width=66)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(background="#6495ed")
        self.Label4.configure(font="-family {DejaVu Sans} -size 12 -weight bold")
        self.Label4.configure(text='''Label''')
        self.Label4.configure(textvariable=self.RunCount)
        self.RunCount.set('''Label''')

class Splash:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("798x450+948+454")
        top.minsize(1, 1)
        top.maxsize(4225, 1410)
        top.resizable(0,  0)
        top.title("Splash")
        top.configure(background="navajowhite3")
        top.configure(highlightcolor="black")

        self.top = top

        self.lblImage = tk.Label(self.top)
        self.lblImage.place(x=10, y=20, height=379, width=396)
        self.lblImage.configure(activebackground="#f9f9f9")
        self.lblImage.configure(anchor='w')
        self.lblImage.configure(background="navajowhite3")
        photo_location = "./graphics/Anonymous-splash.png"
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.lblImage.configure(image=_img0)
        self.lblImage.configure(text='''Label''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(x=420, y=120, height=49, width=356)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="navajowhite3")
        self.Label1.configure(compound='left')
        self.Label1.configure(font="-family {DejaVu Sans} -size 18 -weight bold -slant italic")
        self.Label1.configure(text='''My Splash Screen Demo''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(x=430, y=240, height=23, width=326)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(background="navajowhite3")
        self.Label2.configure(compound='left')
        self.Label2.configure(font="-family {DejaVu Sans} -size 12 -weight bold -slant italic")
        self.Label2.configure(text='''Written by G. D. Walters''')

        self.Label3 = tk.Label(self.top)
        self.Label3.place(x=439, y=355, height=21, width=316)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(background="navajowhite3")
        self.Label3.configure(compound='left')
        self.Label3.configure(text='''Image from OpenClipart.org''')

def start_up():
    DualForms_support.main()

if __name__ == '__main__':
    DualForms_support.main()




