#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.0
#  in conjunction with Tcl version 8.6
#    Dec 28, 2021 04:42:36 AM CST  platform: Linux

import sys
import shared
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import DualForms


def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = DualForms.MainForm(_top1)
    # Creates a toplevel widget.
    global _top2, _w2
    _top2 = tk.Toplevel(root)
    _w2 = DualForms.ChildForm(_top2)
    startup()
    root.mainloop()


def startup():
    shared.childrunning = False
    shared.childruncount = 0
    shared.passback = ''
    hide_form2()


def on_btnDismiss(*args):
    print('DualForms_support.on_btnDismiss')
    for arg in args:
        print('another arg:', arg)
    sys.stdout.flush()
    hide_form2()
    shared.passback = _w2.PassBack.get()
    if shared.passback != '':
        _w1.SecondFormData.set(shared.passback)
    _w1.che46.set(1)

    show_Main()


def on_btnExit(*args):
    print('DualForms_support.on_btnExit')
    for arg in args:
        print('another arg:', arg)
    sys.stdout.flush()
    root.destroy()


def on_btnLaunch(*args):
    print('DualForms_support.on_btnLaunch')
    for arg in args:
        print('another arg:', arg)
    sys.stdout.flush()
    hide_Main()
    shared.childruncount += 1
    _w2.RunCount.set(shared.childruncount)
    shared.passback = ''
    _w2.PassBack.set('')
    show_Form2()


def show_Main():
    # pass
    _top1.deiconify()


def show_Form2():
    # pass
    _top2.deiconify()


def hide_Main():
    # pass
    _top1.withdraw()


def hide_form2():
    # pass
    _top2.withdraw()


if __name__ == '__main__':
    DualForms.start_up()
