#############################################################################
# Generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#  Oct 22, 2022 03:49:06 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    document_new_png "./Assets/document-new.png" 
    document_open_png "./Assets/document-open.png" 
    document_save_png "./Assets/document-save.png" 
    document_save_as_png "./Assets/document-save-as.png" 
    system_log_out_png "./Assets/system-log-out.png" 
    help_contents32_png "./Assets/help-contents32.png" 
    information_png "./Assets/information.png" 
    edit_copy_png "./Assets/edit-copy.png" 
    edit_clear_png "./Assets/edit-clear.png" 
    edit_paste_png "./Assets/edit-paste.png" 
    edit_cut_png "./Assets/edit-cut.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}



    vTcl::widgets::core::popup::createCmd .pop46 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkMenuFont \
        -foreground $vTcl(actual_gui_fg) -tearoff 1 
    global vTcl
    set val vTcl(.pop46,-proc)
    set vTcl(.pop46,-proc) popup1
    namespace eval ::widgets::.pop46 {}
    set ::widgets::.pop46::ClassOption(-proc) popup1
    set ::widgets::.pop46::options(-proc) popup1
    set ::widgets::.pop46::save(-proc) 1
    vTcl:DefineAlias ".pop46" "Popupmenu1" vTcl:WidgetProc "" 1
    .pop46 add command \
        -command {#lambda : on_pop_Copy(args[0])} -label Copy 
    .pop46 add command \
        -command {#lambda : on_pop_Cut(args[0])} -label Cut 
    .pop46 add command \
        -command {#lambda : on_pop_Paste(args[0])} -label Paste 
    .pop46 add command \
        -command {#lambda : on_pop_Clear(args[0])} -label Clear 
    .pop46 add command \
        -command {#lambda : on_pop_Quit(args[0])} -label Quit 
    .pop46 add separator \
        
    .pop46 add command \
        -command {#lambda : on_pop_CloseMenu(args[0])} -label {Close Menu} 

proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m48" -background $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+399+256
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4225 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Menu Demo"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    entry $top.ent47 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black \
        -textvariable EntryData -width 166 
    vTcl:DefineAlias "$top.ent47" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    bind $top.ent47 <Button-3> {
        lambda e: popup1(e, 1)
    }
    menu $top.m48 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    
set site_3_0 $top.m48
    $top.m48 add cascade \
        -menu "$top.m48.men49" -label File 
    menu $site_3_0.men49 \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $site_3_0.men49 add command \
        -command {#on_mnu_FileNew} -label New 
    $site_3_0.men49 add command \
        -command {#on_mnu_FileOpen} -label Open 
    $site_3_0.men49 add command \
        -command {#on_mnu_FileSave} -label Save 
    $site_3_0.men49 add command \
        -command {#on_mnu_FileSaveAs} -label {Save As} 
    $site_3_0.men49 add separator \
        
    $site_3_0.men49 add command \
        -command {#on_mnu_FileQuit} -label Quit 
    
set site_3_0 $top.m48
    $top.m48 add cascade \
        -menu "$top.m48.men50" -label Help 
    menu $site_3_0.men50 \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $site_3_0.men50 add command \
        -command {#on_mnu_HelpAbout} -label About 
    $site_3_0.men50 add separator \
        
    $site_3_0.men50 add command \
        -command {#on_mnu_HelpHelp} -label Help 
    entry $top.ent46 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black \
        -textvariable EntryData2 -width 166 
    vTcl:DefineAlias "$top.ent46" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 45 -highlightcolor black -width 595 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_btnFileNew -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image document_new_png 
    vTcl:DefineAlias "$site_3_0.but47" "btnFileNew" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {File New}
    }
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_btnFileOpen -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image document_open_png 
    vTcl:DefineAlias "$site_3_0.but48" "btnFileOpen" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {File Open}
    }
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_btnFileSave -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image document_save_png 
    vTcl:DefineAlias "$site_3_0.but49" "btnFileSave" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {File Save}
    }
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_btn_FileSaveAs -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image document_save_as_png 
    vTcl:DefineAlias "$site_3_0.but50" "btnFileSaveAs" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {File Save As}
    }
    button $site_3_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnExit \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image system_log_out_png 
    vTcl:DefineAlias "$site_3_0.but51" "btnAppExit" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Exit App}
    }
    button $site_3_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnHelp \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image help_contents32_png 
    vTcl:DefineAlias "$site_3_0.but52" "btnHelp" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Help}
    }
    button $site_3_0.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnInfo \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image information_png 
    vTcl:DefineAlias "$site_3_0.but53" "btnAbout" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {About}
    }
    button $site_3_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btn_Copy \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image edit_copy_png 
    vTcl:DefineAlias "$site_3_0.but54" "btnCopy" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Copy}
    }
    button $site_3_0.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnClear \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image edit_clear_png 
    vTcl:DefineAlias "$site_3_0.but55" "btnClear" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Clear}
    }
    button $site_3_0.but56 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnPaste \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image edit_paste_png 
    vTcl:DefineAlias "$site_3_0.but56" "btnPaste" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but56 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Paste}
    }
    button $site_3_0.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnCut \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image edit_cut_png 
    vTcl:DefineAlias "$site_3_0.but57" "btnCut" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but57 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Cut}
    }
    place $site_3_0.but47 \
        -in $site_3_0 -x 5 -y 3 -width 36 -relwidth 0 -height 36 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 40 -y 3 -width 36 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 75 -y 3 -width 36 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 110 -y 3 -width 36 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 552 -y 3 -width 36 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 445 -y 3 -width 36 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 410 -y 3 -width 36 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 179 -y 3 -width 36 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 215 -y 3 -width 36 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 250 -y 3 -width 36 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but57 \
        -in $site_3_0 -x 285 -y 3 -width 36 -height 36 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent47 \
        -in $top -x 160 -y 160 -width 166 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 160 -y 220 -width 166 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 4 -y 2 -width 595 -relwidth 0 -height 48 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

