#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7x
#  in conjunction with Tcl version 8.6
#    Oct 15, 2021 03:33:25 AM CDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import firstproject


def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = firstproject.Firstproject(_top1)
    init()
    root.mainloop()


def init():
    _w1.DynamicLabelText.set("Hi!  I am a dynamic Label")
    _w1.selectedButton.set(0)
    _w1.RbSelectDisplay.set("")


def on_btnExit(*args):
    print('firstproject_support.on_btnExit')
    for arg in args:
        print('another arg:', arg)
    sys.stdout.flush()
    root.destroy()


def on_btnGrabEntry(*args):
    print('firstproject_support.on_btnGrabEntry')
    for arg in args:
        print('another arg:', arg)
    sys.stdout.flush()
    Entered = _w1.EntryData.get()
    _w1.DynamicLabelText.set(Entered)


def on_rbClick(*args):
    print('firstproject_support.on_rbClick')
    for arg in args:
        print('another arg:', arg)
    sys.stdout.flush()
    WhichSelected = _w1.selectedButton.get()
    if WhichSelected == 0:
        _w1.RbSelectDisplay.set('You picked "NO"')
    else:
        _w1.RbSelectDisplay.set('You picked "YES"')


if __name__ == '__main__':
    firstproject.start_up()
