#############################################################################
# Generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#  Sep 29, 2022 04:28:40 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    applications_graphics_png "./Assets/applications-graphics.png" 
    edit_clear_png "./Assets/edit-clear.png" 
    internet_png "./Assets/internet.png" 
    system_run_png "./Assets/system-run.png" 
    checkbox_unchecked_png "./Assets/checkbox-unchecked.png" 
    checkbox_checked_png "./Assets/checkbox-checked.png" 
    radio_unchecked_png "./Assets/radio-unchecked.png" 
    radio_checked_png "./Assets/radio-checked.png" 
    information_png "./Assets/information.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m51" -background $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x474+745+399
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4225 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Chapter 5 Graphics"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image applications_graphics_png -text Button 
    vTcl:DefineAlias "$top.but46" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound right \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image edit_clear_png -padx 8 -relief groove \
        -text Label 
    vTcl:DefineAlias "$top.lab47" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu49 \
        -takefocus {} -text Tbutton -image internet_png -compound top 
    vTcl:DefineAlias "$top.tBu49" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa50 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief groove -anchor center -justify left \
        -text Tlabel -image system_run_png -compound bottom 
    vTcl:DefineAlias "$top.tLa50" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m51 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    
set site_3_0 $top.m51
    $top.m51 add cascade \
        -menu "$top.m51.men52" -label {Image Menu Item} 
    menu $site_3_0.men52 \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $site_3_0.men52 add command \
        -command {#on_mnu_Click_me} -compound left -image information_png \
        -label {Click me!} 
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor e \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify right \
        -text {Tk Button - Compound left, Anchor w} -wraplength 140 
    vTcl:DefineAlias "$top.lab53" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor e \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify right \
        -text {Tk Label - Compound right} -wraplength 130 
    vTcl:DefineAlias "$top.lab54" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor e \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify right \
        -text {ttk Button - Compound Top} -wraplength 145 
    vTcl:DefineAlias "$top.lab55" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor e \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify right \
        -text {ttk TLabel - Compound Bottom} -wraplength 145 
    vTcl:DefineAlias "$top.lab56" "Label5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$top.but57" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief groove \
        -text Label 
    vTcl:DefineAlias "$top.lab58" "Label6" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu59 \
        -takefocus {} -text Tbutton -compound left 
    vTcl:DefineAlias "$top.tBu59" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa60 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief groove -anchor w -justify left \
        -text Tlabel -compound left 
    vTcl:DefineAlias "$top.tLa60" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab46" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab48" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab49" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab50" "Label10" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che46 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image checkbox_unchecked_png -indicatoron 0 \
        -justify left -padx 4 -selectcolor #d9d9d9 \
        -selectimage checkbox_checked_png -text Check -variable che46 
    vTcl:DefineAlias "$top.che46" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad47 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image radio_unchecked_png -indicatoron 0 \
        -justify left -padx 4 -selectcolor #d9d9d9 \
        -selectimage radio_checked_png -text Radio -value 1 \
        -variable selectedButton 
    vTcl:DefineAlias "$top.rad47" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but46 \
        -in $top -x 170 -y 30 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 170 -y 110 -width 102 -relwidth 0 -height 42 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu49 \
        -in $top -x 170 -y 166 -width 83 -relwidth 0 -height 64 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa50 \
        -in $top -x 170 -y 260 -width 82 -relwidth 0 -height 62 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 50 -y 10 -width 109 -relwidth 0 -height 91 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 50 -y 110 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 50 -y 177 -width 102 -relwidth 0 -height 38 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 20 -y 270 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 300 -y 30 -width 116 -relwidth 0 -height 48 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 300 -y 110 -width 102 -relwidth 0 -height 42 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu59 \
        -in $top -x 300 -y 166 -width 83 -relwidth 0 -height 64 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa60 \
        -in $top -x 300 -y 260 -width 82 -relwidth 0 -height 62 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 450 -y 7 -width 109 -relwidth 0 -height 91 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 440 -y 86 -width 109 -relwidth 0 -height 91 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 440 -y 156 -width 109 -relwidth 0 -height 91 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 430 -y 245 -width 109 -relwidth 0 -height 91 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che46 \
        -in $top -x 100 -y 360 -width 127 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.rad47 \
        -in $top -x 100 -y 400 -width 138 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

