#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Dec 21, 2022 05:35:22 AM CST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import scldemo_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Main:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("706x653+689+265")
        top.minsize(1, 1)
        top.maxsize(4225, 1410)
        top.resizable(0,  0)
        top.title("ScrolledCheckedListbox Demo")
        top.configure(background="bisque4")

        self.top = top

        self.btnExit = tk.Button(self.top)
        self.btnExit.place(x=540, y=40, height=33, width=103)
        self.btnExit.configure(activebackground="beige")
        self.btnExit.configure(borderwidth="2")
        self.btnExit.configure(command=scldemo_support.on_btnExit)
        self.btnExit.configure(compound='left')
        self.btnExit.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.btnExit.configure(text='''Exit''')
        self.Message1 = tk.Message(self.top)
        self.Message1.place(x=40, y=200, height=71, width=322)
        self.Message1.configure(padx="1")
        self.Message1.configure(pady="1")
        self.Message1.configure(text='''Message''')
        self.Message1.configure(width=322)
        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(x=40, y=290, height=345, width=305)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Custom1 = scldemo_support.Custom(self.Frame1)
        self.Custom1.place(x=0, y=0, height=345, width=305)
        self.btnGetChecks = tk.Button(self.top)
        self.btnGetChecks.place(x=410, y=320, height=33, width=163)
        self.btnGetChecks.configure(activebackground="beige")
        self.btnGetChecks.configure(borderwidth="2")
        self.btnGetChecks.configure(command=scldemo_support.on_btnGetChecks)
        self.btnGetChecks.configure(compound='left')
        self.btnGetChecks.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.btnGetChecks.configure(text='''Get Checks''')
        self.btnClearChecks = tk.Button(self.top)
        self.btnClearChecks.place(x=410, y=380, height=33, width=163)
        self.btnClearChecks.configure(activebackground="beige")
        self.btnClearChecks.configure(borderwidth="2")
        self.btnClearChecks.configure(command=scldemo_support.on_btnClearChecks)
        self.btnClearChecks.configure(compound='left')
        self.btnClearChecks.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.btnClearChecks.configure(text='''Clear Checks''')
        self.btnSwitchMode = tk.Button(self.top)
        self.btnSwitchMode.place(x=420, y=480, height=33, width=153)
        self.btnSwitchMode.configure(activebackground="beige")
        self.btnSwitchMode.configure(borderwidth="2")
        self.btnSwitchMode.configure(command=scldemo_support.on_btnSwitchMode)
        self.btnSwitchMode.configure(compound='left')
        self.btnSwitchMode.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.btnSwitchMode.configure(text='''Switch Mode''')

def start_up():
    scldemo_support.main()

if __name__ == '__main__':
    scldemo_support.main()




