#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Jan 16, 2023 03:13:27 AM CST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    go_first_png "./graphics/go-first.png" 
    go_previous_png "./graphics/go-previous.png" 
    go_next_png "./graphics/go-next.png" 
    go_last_png "./graphics/go-last.png" 
    system_shutdown_png "./graphics/system-shutdown.png" 
    view_refresh_png "./graphics/view-refresh.png" 
    edit_find_png "./graphics/edit-find.png" 
    accessories_text_editor_png "./graphics/accessories-text-editor.png" 
    list_add_png "./graphics/list-add.png" 
    list_remove_png "./graphics/list-remove.png" 
    information_png "./graphics/information.png" 
    question_png "./graphics/question.png" 
    document_save_png "./graphics/document-save.png" 
    edit_undo_png "./graphics/edit-undo.png" 
    accessories_text_editor_no_png "./graphics/accessories-text-editor-No.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 998x516+872+359
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Database Viewer"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Main" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame "$top.tFr54" \
        -borderwidth 2 -relief groove -width 125 -height 75 
    vTcl:DefineAlias "$top.tFr54" "TFrame3" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.tFr54
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame "$site_3_0.tFr55" \
        -borderwidth 2 -relief sunken -width 125 -height 75 
    vTcl:DefineAlias "$site_3_0.tFr55" "TFrame2" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.tFr55
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame "$site_4_0.tFr56" \
        -borderwidth 2 -relief sunken -width 365 -height 55 
    vTcl:DefineAlias "$site_4_0.tFr56" "TFrame1" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    set site_5_0 $site_4_0.tFr56
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_5_0.tBu48" \
        -command "on_btnGoFirst" -takefocus {} -image go_first_png \
        -compound none -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_5_0.tBu48" "TButton1" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_5_0.tBu48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Go to First Record}
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_5_0.tBu49" \
        -command "on_btnGoPrevious" -takefocus {} -image go_previous_png \
        -compound none -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_5_0.tBu49" "TButton2" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_5_0.tBu49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Go to Previous Record}
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_5_0.tBu50" \
        -command "on_btnGoNext" -takefocus {} -image go_next_png \
        -compound none -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_5_0.tBu50" "TButton3" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_5_0.tBu50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Go To Next Record}
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_5_0.tBu51" \
        -command "on_btnGoLast" -takefocus {} -image go_last_png \
        -compound none -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_5_0.tBu51" "TButton4" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_5_0.tBu51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Go To Last Record}
    }
    ttk::entry "$site_5_0.tEn52" \
        -font "TkTextFont" -textvariable "EntryRecordInfo" -foreground {} \
        -background {} -takefocus False -cursor xterm 
    vTcl:DefineAlias "$site_5_0.tEn52" "TEntry1" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    place $site_5_0.tBu48 \
        -in $site_5_0 -x 5 -y 2 -width 42 -relwidth 0 -height 42 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_5_0.tBu49 \
        -in $site_5_0 -x 50 -y 2 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu50 \
        -in $site_5_0 -x 270 -y 2 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu51 \
        -in $site_5_0 -x 316 -y 2 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tEn52 \
        -in $site_5_0 -x 100 -y 13 -width 164 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::label "$site_4_0.tLa52" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief sunken -anchor center -justify left \
        -textvariable "::StatusTime" -compound left 
    vTcl:DefineAlias "$site_4_0.tLa52" "TLabel12" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::label "$site_4_0.tLa48" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "TkDefaultFont" -relief sunken -anchor w -justify left \
        -textvariable "::RecordNumber" -compound left 
    vTcl:DefineAlias "$site_4_0.tLa48" "TLabel13" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    place $site_4_0.tFr56 \
        -in $site_4_0 -x 3 -y 1 -width 365 -relwidth 0 -height 55 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa52 \
        -in $site_4_0 -x 810 -y 1 -width 182 -relwidth 0 -height 55 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa48 \
        -in $site_4_0 -x 371 -y 1 -width 435 -relwidth 0 -height 53 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu57" \
        -command "on_tbtnExit" -takefocus {} -text "Exit" \
        -image system_shutdown_png -compound left -style "Toolbutton" \
        -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu57" "btnExit" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_3_0.tBu57 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Exit the Program}
    }
    ttk::label "$site_3_0.tLa58" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor e -justify left -text "First Name:" \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tLa58" "TLabel1" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::label "$site_3_0.tLa59" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor e -justify left -text "Middle Name:" \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tLa59" "TLabel2" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::label "$site_3_0.tLa60" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor e -justify left -text "Last Name:" \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tLa60" "TLabel3" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::label "$site_3_0.tLa61" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor e -justify left -text "Address 1:" \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tLa61" "TLabel4" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::label "$site_3_0.tLa62" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor e -justify left -text "Address 2:" \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tLa62" "TLabel5" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::label "$site_3_0.tLa63" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor e -justify left -text "City:" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa63" "TLabel6" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::label "$site_3_0.tLa64" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor e -justify left -text "State:" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa64" "TLabel7" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::label "$site_3_0.tLa65" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor e -justify left -text "Postal Code:" \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tLa65" "TLabel8" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::label "$site_3_0.tLa66" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor e -justify left -text "Date of Birth:" \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tLa66" "TLabel9" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::label "$site_3_0.tLa67" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor e -justify left -text "Phone Number:" \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tLa67" "TLabel10" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::combobox "$site_3_0.tCo68" \
        -font "TkTextFont" -textvariable "combobox" -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo68" "TCombobox1" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::label "$site_3_0.tLa69" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor e -justify left -text "Department" \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tLa69" "TLabel11" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::entry "$site_3_0.tEn70" \
        -font "TkTextFont" -textvariable "EntryFirstName" -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn70" "TEntFName" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::entry "$site_3_0.tEn71" \
        -font "TkTextFont" -textvariable "EntryMiddleName" -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn71" "TEntMName" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::entry "$site_3_0.tEn72" \
        -font "TkTextFont" -textvariable "EntryLastName" -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn72" "TEntLName" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::entry "$site_3_0.tEn73" \
        -font "TkTextFont" -textvariable "EntryAddr1" -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn73" "TEntAddr1" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::entry "$site_3_0.tEn74" \
        -font "TkTextFont" -textvariable "EntryAddr2" -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn74" "TEntAddr2" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::entry "$site_3_0.tEn75" \
        -font "TkTextFont" -textvariable "EntryCity" -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn75" "TEntCity" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::entry "$site_3_0.tEn76" \
        -font "TkTextFont" -textvariable "EntryState" -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn76" "TEntState" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::entry "$site_3_0.tEn77" \
        -font "TkTextFont" -textvariable "EntryPostal" -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn77" "TEntPostal" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::entry "$site_3_0.tEn78" \
        -font "TkTextFont" -textvariable "EntryDOB" -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn78" "TEntDOB" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::entry "$site_3_0.tEn79" \
        -font "TkTextFont" -textvariable "EntryPhone" -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn79" "TEntPhone" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu47" \
        -command "on_btnChangeTheme" -takefocus {} -image view_refresh_png \
        -compound none -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu47" "TButton5" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_3_0.tBu47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Change Theme}
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu48" \
        -command "on_btnSearch" -takefocus {} -text "Tbutton" \
        -image edit_find_png -compound none -style "Toolbutton" \
        -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu48" "TButton6" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_3_0.tBu48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Search for Last Name}
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu49" \
        -command "on_btnEdit" -takefocus {} -text "Tbutton" \
        -image accessories_text_editor_png -compound none -style "Toolbutton" \
        -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu49" "btnEdit" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_3_0.tBu49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Edit Current Record}
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu50" \
        -command "on_btnAdd" -takefocus {} -text "Tbutton" \
        -image list_add_png -compound none -style "Toolbutton" \
        -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu50" "TButton8" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_3_0.tBu50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Add New Employee}
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu51" \
        -command "on_btnDelete" -takefocus {} -text "Tbutton" \
        -image list_remove_png -compound none -style "Toolbutton" \
        -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu51" "TButton9" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_3_0.tBu51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Delete Employee}
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu53" \
        -command "on_btnAbout" -takefocus {} -text "Tbutton" \
        -image information_png -compound none -style "Toolbutton" \
        -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu53" "TButton10" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_3_0.tBu53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {About}
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu54" \
        -command "on_btnHelp" -takefocus {} -text "Tbutton" \
        -image question_png -compound none -style "Toolbutton" \
        -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu54" "TButton11" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_3_0.tBu54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Help}
    }
    label "$site_3_0.lab55" \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief raised 
    vTcl:DefineAlias "$site_3_0.lab55" "Label1" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab57" \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief raised 
    vTcl:DefineAlias "$site_3_0.lab57" "Label1_1" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu52" \
        -command "on_btnSave" -takefocus {} -text "Tbutton" \
        -image document_save_png -compound none -state disabled \
        -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu52" "btnSave" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_3_0.tBu52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Save Changes}
    }
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton "$site_3_0.tCh47" \
        -variable "tch47" -command "on_TCheck" -takefocus {} \
        -text "Show All Records" -compound left 
    vTcl:DefineAlias "$site_3_0.tCh47" "TCheckbutton1" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu55" \
        -command "on_btnUndoDelete" -takefocus {} -text "Tbutton" \
        -image edit_undo_png -compound none -style "Toolbutton" \
        -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu55" "btnRestore" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_3_0.tBu55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Undo Delete}
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu56" \
        -command "on_btnCancelEdit" -takefocus {} -text "Tbutton" \
        -image accessories_text_editor_no_png -compound none \
        -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu56" "btnUnEdit" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    bind $site_3_0.tBu56 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Exit Edit Mode}
    }
    place $site_3_0.tFr55 \
        -in $site_3_0 -x 0 -y 440 -width 996 -relwidth 0 -height 60 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu57 \
        -in $site_3_0 -x 870 -y 20 -width 99 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa58 \
        -in $site_3_0 -x 10 -y 100 -width 122 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa59 \
        -in $site_3_0 -x 320 -y 100 -width 122 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa60 \
        -in $site_3_0 -x 630 -y 100 -width 122 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa61 \
        -in $site_3_0 -x 10 -y 150 -width 122 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa62 \
        -in $site_3_0 -x 420 -y 150 -width 122 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa63 \
        -in $site_3_0 -x 10 -y 200 -width 122 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa64 \
        -in $site_3_0 -x 380 -y 200 -width 82 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa65 \
        -in $site_3_0 -x 680 -y 200 -width 112 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa66 \
        -in $site_3_0 -x 30 -y 300 -width 122 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa67 \
        -in $site_3_0 -x 360 -y 300 -width 122 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo68 \
        -in $site_3_0 -x 160 -y 380 -width 187 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa69 \
        -in $site_3_0 -x 10 -y 380 -width 122 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn70 \
        -in $site_3_0 -x 140 -y 100 -width 164 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn71 \
        -in $site_3_0 -x 450 -y 100 -width 164 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn72 \
        -in $site_3_0 -x 760 -y 100 -width 164 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn73 \
        -in $site_3_0 -x 150 -y 150 -width 254 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn74 \
        -in $site_3_0 -x 550 -y 150 -width 254 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn75 \
        -in $site_3_0 -x 150 -y 200 -width 204 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn76 \
        -in $site_3_0 -x 480 -y 200 -width 184 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn77 \
        -in $site_3_0 -x 800 -y 200 -width 144 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn78 \
        -in $site_3_0 -x 170 -y 300 -width 164 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn79 \
        -in $site_3_0 -x 500 -y 300 -width 254 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu47 \
        -in $site_3_0 -x 650 -y 20 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu48 \
        -in $site_3_0 -x 552 -y 20 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu49 \
        -in $site_3_0 -x 238 -y 20 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu50 \
        -in $site_3_0 -x 350 -y 20 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu51 \
        -in $site_3_0 -x 409 -y 20 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu53 \
        -in $site_3_0 -x 737 -y 20 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu54 \
        -in $site_3_0 -x 790 -y 20 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 9 -y 72 -width 979 -relwidth 0 -height 3 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 9 -y 253 -width 979 -height 3 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu52 \
        -in $site_3_0 -x 297 -y 20 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCh47 \
        -in $site_3_0 -x 20 -y 30 -width 144 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu55 \
        -in $site_3_0 -x 473 -y 20 -width 42 -height 42 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu56 \
        -in $site_3_0 -x 187 -y 20 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tFr54
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr54 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

